### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by EmanueleZof** [Tencent/MimicMotion#105]
I'm encountering this error, while using 16-frames model:
```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
2024-12-05 19:44:10.814971: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-05 19:44:10.834753: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-05 19:44:10.844499: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-05 19:44:10.858943: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-05 19:44:12.004969: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
unet/config.json: 100% 984/984 [00:00<00:00, 6.98MB/s]
vae/config.json: 100% 607/607 [00:00<00:00, 4.14MB/s]
diffusion_pytorch_model.fp16.safetensors: 100% 196M/196M [00:04<00:00, 41.9MB/s]
image_encoder/config.json: 100% 685/685 [00:00<00:00, 4.69MB/s]
model.fp16.safetensors: 100% 1.26G/1.26G [00:29<00:00, 42.3MB/s]
scheduler/scheduler_config.json: 100% 533/533 [00:00<00:00, 3.66MB/s]
(…)ature_extractor/preprocessor_config.json: 100% 518/518 [00:00<00:00, 3.89MB/s]
/content/MimicMotion/mimicmotion/utils/loader.py:43: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mimicmotion_models.load_state_dict(torch.load(infer_config.ckpt_path, map_location="cpu"), strict=False)
/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
DWPose: 100% 176/176 [08:00<00:00,  2.73s/it]
100% 300/300 [42:09<00:00,  8.43s/it]
Traceback (most recent call last):
  File "/content/MimicMotion/inference.py", line 136, in <module>
    main(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/MimicMotion/inference.py", line 106, in main
    save_to_mp4(
  File "/content/MimicMotion/mimicmotion/utils/utils.py", line 11, in save_to_mp4
    write_video(save_path, frames, fps=fps)
  File "/usr/local/lib/python3.10/dist-packages/torchvision/io/video.py", line 140, in write_video
    frame.pict_type = "NONE"
  File "av/video/frame.pyx", line 193, in av.video.frame.VideoFrame.pict_type.__set__
TypeError: an integer is required
```

**Comment by EnochYe** [comment]
Downgrade to av-12.0.0

**Comment by EmanueleZof** [comment]
Perfect, it works fine.
Thanks for the help, this issue could be closed.

**Comment by v-iashin** [comment]
also works with slightly higher version than the one suggested above `av==13.1.0`
