### ISSUE TITLE
第一阶段是用CPU处理吗？

### ISSUE THREAD

**Issue by theoldsong** [Tencent/MimicMotion#40]
UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
DWPose: 这个阶段一直用的CPU，是正常的吗？
然后第二阶段处理是用的GPU

**Comment by theoldsong** [comment]
4080super 20s用了两个小时，这正常吗？

**Comment by theoldsong** [comment]
Video will be saved to: E:\python\MimicMotion\outputs\sc2[20240713-211452]_2024-07-14_10-42-57.mp4
Traceback (most recent call last):
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\python\MimicMotion\app.py", line 85, in run_MimicMotion
    save_to_mp4(_video_frames, path_out_vid, fps=task.fps)
  File "E:\python\MimicMotion\mimicmotion\utils\utils.py", line 11, in save_to_mp4
    write_video(save_path, frames, fps=fps)
  File "D:\anaconda3\envs\mimicmotion\Lib\site-packages\torchvision\io\video.py", line 91, in write_video
    stream = container.add_stream(video_codec, rate=fps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\\container\\output.pyx", line 67, in av.container.output.OutputContainer.add_stream
  File "av\\codec\\codec.pyx", line 185, in av.codec.codec.Codec.__cinit__
  File "av\\codec\\codec.pyx", line 194, in av.codec.codec.Codec._init
av.codec.codec.UnknownCodecError: libx264

两个小时后，居然还报错了。。。

**Comment by zyayoung** [comment]
是的，可以自行安装onnxruntime-gpu使用GPU。可参考https://github.com/Tencent/MimicMotion/issues/44#issue-2409997835

**Comment by zyayoung** [comment]
速度问题可参考https://github.com/Tencent/MimicMotion/issues/27，目前看在linux系统没有问题，可能与windows系统有关
