### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by pavelxx1** [Tencent/MimicMotion#41]
Most of tested videos I have same issue
```
DWPose: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 164/164 [01:40<00:00,  1.64it/s]
Traceback (most recent call last):
  File "/workspace/MimicMotion/inference.py", line 136, in <module>
    main(args)
  File "/root/miniconda3/envs/mimicmotion/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/MimicMotion/inference.py", line 95, in main
    pose_pixels, image_pixels = preprocess(
                                ^^^^^^^^^^^
  File "/workspace/MimicMotion/inference.py", line 58, in preprocess
    video_pose = get_video_pose(video_path, image_pixels, sample_stride=sample_stride)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/MimicMotion/mimicmotion/dwpose/preprocess.py", line 40, in get_video_pose
    detected_bodies = np.stack(
                      ^^^^^^^^^
  File "/root/miniconda3/envs/mimicmotion/lib/python3.11/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by zyayoung** [comment]
It appears that no body has been detected in the provided video.

**Comment by pavelxx1** [comment]
@zyayoung Yes, but not) Body fully viewed on video , but I have issue
[test_vid.mp4](https://github.com/pavelxx1/test_vid/raw/main/aa.mp4)

**Comment by pavelxx1** [comment]
@zyayoung Can u check ?

**Comment by Pythonpa** [comment]
The same ,  Such problems do occur in some videos. 
At first, I thought it was because there were more than one person in the video. 
However, when I continued to test, I did not encounter such problems in some videos in which two people appeared.

**Comment by ansorre** [comment]
Has this problem been solved? Because I'm getting it too!

**Comment by MauricioTonon** [comment]
yeah, so anything makes the tool useless. Any solution?
