### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ximo2002** [Tencent/MimicMotion#74]
(mimicmotion) root@ddjd3:~/project/MimicMotion# python inference.py --inference_config configs/test.yaml
2024-08-12 15:01:12.347972725 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-08-12 15:01:12.347998906 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
DWPose: 100%|███████████████████████████████████████████████████████████| 62/62 [00:02<00:00, 28.33it/s]
Traceback (most recent call last):
  File "/root/project/MimicMotion/inference.py", line 140, in <module>
    main(args)
  File "/root/miniconda3/envs/mimicmotion/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/MimicMotion/inference.py", line 104, in main
    _video_frames = run_pipeline(
                    ^^^^^^^^^^^^^
  File "/root/project/MimicMotion/inference.py", line 72, in run_pipeline
    frames = pipeline(
             ^^^^^^^^^
  File "/root/miniconda3/envs/mimicmotion/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/project/MimicMotion/mimicmotion/pipelines/pipeline_mimicmotion.py", line 549, in __call__
    if indices[-1][-1] < num_frames - 1:
       ~~~~~~~^^^^
IndexError: list index out of range

**Comment by 2623238476** [comment]
你传递的参数，视频总帧数那里看看。他这块逻辑有点乱

**Comment by soltkreig** [comment]
Have the same trouble, my video is less than 1 sec, how I can run mimic on it?

**Comment by ximo2002** [comment]
> 你传递的参数，视频总帧数那里看看。他这块逻辑有点乱

这里是有什么要求嘛，还是要怎么对应才行呀

**Comment by ykykkun** [comment]
视频长度不够，你传76，fps 30的话，视频要有2秒多。

**Comment by ALLLLLLLLA** [comment]
> 视频长度不够，你传76，fps 30的话，视频要有2秒多。

你好，我想问一下，视频总帧数，帧率，分辨率，是不是都要改成自己上传的视频模板的格式，还是只要时间能对上就可以

**Comment by Provemj** [comment]
first, open the config yaml file and make sure that the fps corresponds with that of your video
then, check the "num of frame" in that config file, and set it to be lower than the total frame number of your input video
